### PR TITLE
Exit with original epubcheck command status

### PR DESCRIPTION
**Pull request by hanachin**

### CODE REVIEW

**Comment by takahashim** [comment]
@hanachin  Thanks for your PR!
I like this feature, but I don't like to use cucumber for the project, because the project is for developers so I want to write acceptance tests in Ruby (not in English).
Do you have any recommendations of testing framework for CLI application other than cucumber?

**Comment by takahashim** [comment]
Or should I write acceptance tests with the Plain Old Test::Unit...?

**Comment by hanachin** [comment]
I found a aruba gem that helps testing CLI easier.

> Test command-line applications with Cucumber-Ruby, RSpec or Minitest
https://github.com/cucumber/aruba

For example, Hanami project use aruba with rspec to test the cli.
https://github.com/hanami/hanami/blob/master/spec/support/cli.rb

**Comment by hanachin** [comment]
I have no strong opinion for testing CLI. I think Plain Old Test::Unit is good enough to test the exe/epubcheck 👍

**Comment by takahashim** [comment]
Thanks!  I'll merge only 65ec74f (not c3f7878 ) and remove some code related cucumber.

**Comment by takahashim** [comment]
I've released v4.0.2.1. Thanks again!

**Comment by hanachin** [comment]
I appreciate it,Thank you very much✨

**Pull request closed without merging**
